#!/usr/bin/env bash

# Try to check if Secure Boot is enabled and warn in case it isn't
if command -v mokutil &>/dev/null; then
  if mokutil --sb-state | grep -q -v "SecureBoot enabled"; then
    echo "Warning: Secure Boot is not enabled" >&2
  fi
else
  echo "Warning: mokutil not found, could not check Secure Boot status" >&2
fi

mapfile -t luksdisks < <(lsblk -p --json | jq -r 'path(.. | select(.=="crypt")) as $p | getpath($p[:-3]) | .name')

ask() {
  while :; do
    prompt="  Automatically decrypt using the TPM? [Y/n]"
    read -rp "${prompt}" choice
    case "${choice}" in
    y | Y | "") return 0 ;;
    n | N) return 1 ;;
    *) echo "  Invalid answer: ${choice}" ;;
    esac
  done
}

if command -v systemd-cryptenroll &>/dev/null; then
  for disk in "${luksdisks[@]}"; do
    echo "Found encrypted disk: ${disk}"
    if ask; then
      echo "  Running systemd-cryptenroll..."
      sudo systemd-cryptenroll "${disk}" --tpm2-device=auto --wipe-slot=tpm2
    fi
  done
else
  # TODO: support clevis
  echo "systemd-cryptenroll not found"
fi
